### PR TITLE
Fix invalidating segments with special chars might not work

### LINKED ISSUE #16: Invalidate Reports UI unable to invalidate segments with '>' or '<' in the segment, incorrectly encoding characters
## Expected Behavior

The Invalidate Reports UI tool should be able to invalidate segments with special characters, such as `>` or `<`

## Current Behavior

When invalidating a segment with either the character `>` or `<` currently results in the following error:
`The segment condition 'actions&gt' is not valid.`
image

## Possible Solution

It seems as though the Invalidate Reports UI is not correctly encoding the segment when invalidating the reports, running the command with the correct URL encoding: `./console core:invalidate-report-data --segment='actions%3E1' --dates=XXX` works to invalidate the reports from an SSH session. 

## Steps to Reproduce (for Bugs)

1. Create a report with at least one condition as either greater than(>) or less than(<)
2. Invalidate that segment in the Invalidate reports plugin in the Administration > System menu

## Your Environment

* Matomo Version: 4.3.1

### PR DESCRIPTION
**Pull request by sgiehl**
### Description:

fixes #16

### Review

* [ ] Functional review done
* [ ] Potential edge cases thought about (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] Usability review done (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] Security review done [see checklist](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] Code review done
* [ ] Tests were added if useful/possible
* [ ] Reviewed for breaking changes
* [ ] Developer changelog updated if needed
* [ ] Documentation added if needed
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by Starker3** [comment]
Tested and working in my local instance :+1:

File: Controller.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function invalidateReports()
             'idSites' => $siteIds,
             'period'  => false,
             'dates'   => implode(',', $dates),
-            'segment' => $segment
+            'segment' => Common::unsanitizeInputValue($segment)
```
Comment (diosmosis) [inline Controller.php]: I wonder if we should use `Request::getRawSegmentFromRequest()` here instead of `Common::getRequestVar()`? Not sure if this would cause other url encoding issues actually...

Comment (sgiehl) [reply Controller.php]: Yes. That should work as well as the segment is send as GET parameter.

**Comment by sgiehl** [comment]
@diosmosis applied the feedback
